language: python
python:
    - "2.7"
install:
    - pwd
    - pip install ansible
    # the following dependency is not auto-installed due to bug in ansible-galaxy:
    - ansible-galaxy install stevetjoa.python-common,1.01 --roles-path=.
    - ansible-playbook -i hosts --connection=local test.yml -vv
script:
    - python test.py
    - ipython --version
