---
- name: Install expect.
  sudo: yes
  apt: pkg=expect state=latest

#- name: Download Anaconda.
#get_url: url=http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-1.9.1-Linux-x86_64.sh 
#dest=. mode=0755 force=no

- name: Install Anaconda.
  command: ./Anaconda-1.9.1-Linux-x86_64.sh -b -p {{ anaconda_path }}

- name: Update Anaconda command-line utility.
  command: "{{ anaconda_path }}/bin/conda update conda"

- name: Update Anaconda packages.
  command: "{{ anaconda_path }}/bin/conda update anaconda"
